name: google_news_article
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2
  dio: ^5.8.0+1
  chucker_flutter: ^1.8.5
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  sizer: ^3.0.5
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  flutter_localization: ^0.3.3
  flutter_dotenv: ^6.0.0
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans_Thai/NotoSansThai-Black.ttf
          weight: 900
